# Generated by Django 4.1.3 on 2022-11-12 10:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=24, unique=True, verbose_name="Category"
                    ),
                ),
                ("user", models.CharField(max_length=24)),
                ("users", models.CharField(max_length=24, null=True)),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subcategoryId",
                        to="users.category",
                    ),
                ),
            ],
        ),
        migrations.AlterField(
            model_name="interest",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="users.category"
            ),
        ),
    ]
