# Generated by Django 4.1.3 on 2022-11-15 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_category_alter_interest_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="name",
            field=models.CharField(max_length=56, unique=True, verbose_name="Category"),
        ),
        migrations.AlterField(
            model_name="category",
            name="user",
            field=models.CharField(max_length=56),
        ),
        migrations.AlterField(
            model_name="category",
            name="users",
            field=models.CharField(max_length=56, null=True),
        ),
    ]
