# Generated by Django 4.1.3 on 2023-01-27 09:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("media", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("users", "0003_alter_category_name_alter_category_user_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Activity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("description", models.CharField(max_length=255)),
                ("link", models.CharField(max_length=255, null=True)),
                ("type", models.CharField(max_length=24)),
                ("time", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "media",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="media.photo",
                    ),
                ),
                (
                    "receipient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="receipientId",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="userId",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
