# Generated by Django 4.1.3 on 2023-02-04 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_activity"),
    ]

    operations = [
        migrations.AddField(
            model_name="activity",
            name="read",
            field=models.BooleanField(default=False),
        ),
    ]
