runtime: custom
env: flex
entrypoint: gunicorn -c gunicorn.conf.py -b :$PORT pulsar.wsgi
network:
  session_affinity: true

beta_settings:
  cloud_sql_instances: "pulsar-inc-1:europe-west1:pulsar"

runtime_config:
  python_version: 3

resources:
  cpu: 1
  memory_gb: 1.0

automatic_scaling:
  min_num_instances: 1
  max_num_instances: 1
