# Generated by Django 4.1.3 on 2022-11-11 19:09

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("media", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=24, unique=True, verbose_name="Category"
                    ),
                ),
                ("user", models.CharField(max_length=24)),
                ("users", models.CharField(max_length=24, null=True)),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subcategoryId",
                        to="authentication.category",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                ("username", models.CharField(max_length=15, unique=True)),
                ("solo", models.BooleanField(default=True)),
                ("fullname", models.CharField(max_length=24)),
                (
                    "email",
                    models.EmailField(
                        max_length=254, null=True, verbose_name="Email Address"
                    ),
                ),
                ("bio", models.CharField(blank=True, max_length=80, null=True)),
                ("date_of_birth", models.DateField(blank=True, null=True)),
                (
                    "date_joined",
                    models.DateField(default=django.utils.timezone.localdate),
                ),
                ("portfolio", models.URLField(blank=True, null=True)),
                ("is_admin", models.BooleanField(default=False)),
                ("is_staff", models.BooleanField(default=False)),
                ("is_superuser", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="categoryid",
                        to="authentication.category",
                    ),
                ),
                (
                    "profile_pic",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="media.photo",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
