# Generated by Django 4.1.3 on 2022-11-12 10:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_category_alter_interest_category"),
        ("challenges", "0002_alter_challenge_category"),
        ("authentication", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="categoryid",
                to="users.category",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(
                default="", max_length=254, verbose_name="Email Address"
            ),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name="Category",
        ),
    ]
