# Generated by Django 4.1.3 on 2022-12-24 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0003_provider"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="provider",
            constraint=models.UniqueConstraint(
                fields=("user", "name"), name="Login Provider"
            ),
        ),
    ]
