# Generated by Django 4.1.3 on 2022-11-11 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Photo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("thumbnail", models.URLField()),
                ("thumbnail_blob", models.CharField(max_length=255, null=True)),
                ("medium", models.URLField()),
                ("medium_blob", models.CharField(max_length=255, null=True)),
                ("high", models.URLField()),
                ("high_blob", models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Video",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("low", models.URLField()),
                ("low_blob", models.CharField(max_length=255, null=True)),
                ("medium", models.URLField()),
                ("medium_blob", models.CharField(max_length=255, null=True)),
                ("high", models.URLField()),
                ("high_blob", models.CharField(max_length=255, null=True)),
            ],
        ),
    ]
